extends Node

enum GAMEMODE { CUBE, SHIP, BALL, WAVE }
enum SPEED { SLOW, NORMAL, FAST, FASTER }
enum ORB { PINK, YELLOW, BLUE }

var SPEED_EFFECTS := {
	SPEED.SLOW: 0.75,
	SPEED.NORMAL: 1.0,
	SPEED.FAST: 1.25,
	SPEED.FASTER: 1.50,
}
